FROM php:7.1-apache-jessie

# Config- und Script-Files
COPY ./global/config/postfix-php.ini /usr/local/etc/php/conf.d/
COPY ./global/config/default-php.ini /usr/local/etc/php/conf.d/
COPY ./global/config/remoteip.conf /etc/apache2/conf-available/
COPY ./global/config/vhost.conf /etc/apache2/sites-available/
COPY ./global/install-global.sh /usr/local/bin/install-global.sh
COPY ./7.1-apache/install-7.1-features.sh /usr/local/bin/install-7.1-features.sh

# dos2unix konvertieren der line separators CRLF -> LF
# https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/
RUN apt-get update && apt-get install -y dos2unix

# RUN IT
RUN	 dos2unix /usr/local/bin/install-global.sh \
	&& chmod +x /usr/local/bin/install-global.sh \
	&& /usr/local/bin/install-global.sh \
	&& dos2unix /usr/local/bin/install-7.1-features.sh \
	&& chmod +x /usr/local/bin/install-7.1-features.sh \
	&& /usr/local/bin/install-7.1-features.sh

CMD ["apache2", "-D FOREGROUND"]

WORKDIR /var/www/html
EXPOSE 80
