FROM marschallelectronics/me_base-php:7.1-apache-jessie

# Config- und Script-Files
COPY ./7.1-apache-sqlsrv/install-sqlsrv.sh /usr/local/bin/install-sqlsrv.sh

# dos2unix konvertieren der line separators CRLF -> LF
# https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/
RUN apt-get update && apt-get install -y dos2unix

# RUN IT
RUN	 dos2unix /usr/local/bin/install-sqlsrv.sh \
	&& chmod +x /usr/local/bin/install-sqlsrv.sh \
	&& /usr/local/bin/install-sqlsrv.sh

CMD ["apache2", "-D FOREGROUND"]

WORKDIR /var/www/html
EXPOSE 80
